server:
  port: 8100
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_order?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate :
      ddl-auto: update
    show_sql: true
  application:
    name: item-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/


jwt:
  expiration: 30
  secretKey: mysecret


